export type {
  Ack,
  BombHitPayload,
  ClickPayload,
  ClickRejectedPayload,
  ClientToServerEvents,
  CreateRoomPayload,
  GameStartedPayload,
  JoinedRoom,
  JoinRoomPayload,
  MatchEndedPayload,
  PixelClaimedPayload,
  PixelSpawnedPayload,
  ReadyPayload,
  ReconnectPayload,
  ResyncPayload,
  RoomErrorCode,
  ScoreboardEntry,
  ServerToClientEvents,
  SocketError,
  TargetChangedPayload,
  TickPayload,
  UpdateSettingsPayload,
} from './socket';
